name: Test build

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v7
    - name: Install Ruby
      uses: ruby/setup-ruby@v1
    - name: Install
      run: bundle install
    - name: Build
      run: rake build
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v7
    - name: Install Ruby
      uses: ruby/setup-ruby@v1
    - name: Install
      run: bundle install
    - name: Check
      run: rake check
